### ISSUE TITLE
Implement regression part

### ISSUE THREAD

**Issue by Vimos** [geffy/tffm#3] opened 2016-07-05 03:51 UTC
Thanks for the great repo, which inspired me on learning tensorflow, I am trying to understand the tffm code line by line.

I am planning to implement the regression part. It's not easy for me, but I would like to give it a try. If anybody have finished this, please give me some hint.

**Comment by geffy** [comment] 2016-07-05 04:08
Hi Vimos, thanks for feedback =)
For regression you just needed to implement your own loss function (MSE, I believe) in core graph instead of logloss (at https://github.com/geffy/tffm/blob/master/core.py#L126). Something like that (not tested):

``` python
 def init_loss(self):
    self.loss = tf.pow(self.outputs - self.train_y, 2)
    self.reduced_loss = tf.reduce_mean(self.loss)
    tf.scalar_summary('loss', self.reduced_loss)
```

And after you can call `.decision_fuction()` to get predictions without sigmoid transformation.

I believe I will implement `TFFMRegression` class in the near future.

**Comment by Vimos** [comment] 2016-07-05 04:14
Hi, geffy, thanks for the quick reply. I will try it on my data, if everything goes well, I'd like to offer some feedback.

**Comment by Vimos** [comment] 2016-07-07 09:34
I am running the code with a big data set, it is big because if no batch size assigned, it reports out of memory.

On this data set, using a GPU GTX970M, with a batch size of 1000, it reports 120s/epoch, which costs **more or equal** time than the original libfm tool.

Now I wonder, what is the best choice for batch size, is it possible automatically choose an optimized batch?

**Comment by geffy** [comment] 2016-07-10 21:17
> On this data set, using a GPU GTX970M, with a batch size of 1000, it reports 120s/epoch, which costs more or equal time than the original libfm tool.

Could you please provide details about the comparison? Dataset size, the number of non-zero features in the single sample, parameters of tffm and libfm models?

> Now I wonder, what is the best choice for batch size, is it possible automatically choose an optimized batch?

It depends on the task, data and optimization method.

**Comment by graytowne** [comment] 2016-07-22 06:11
@Vimos I think libfm is faster because it use an optimized way to compute prediction and gradient(you can see the details in the original paper). 
I think maybe It is a reason but not the only reason.

**Comment by geffy** [comment] 2016-07-23 14:33
@Vimos `TFFMRegression` implemented and merged into master.
If you used my code sample from above -- it contains a bug which can affect performance. 
Please, check current implementation.
I will close this issue, but we still need comparison with libFM.

**Closed as completed by geffy** 2016-07-23 14:33 UTC
